check ci result

diff --git a/.github/workflows/github-actions-es.yml b/.github/workflows/github-actions-es.yml
--- a/.github/workflows/github-actions-es.yml
+++ b/.github/workflows/github-actions-es.yml
@@ -4,7 +4,7 @@ name: GitHub Actions ES
 run-name: ${{ github.actor }} is push code to main 🚀
 on:
   push:
-    branches: [ "main" ]
+    branches: [ "main", "ci-merge" ]
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -21,3 +21,13 @@ jobs:
 
       - name: Test
         run: go test -v ./... -tags ci
+
+      - name: Check build and test results
+        run: |
+          if [ ${{ job.status }} == 'failure' ]; then
+            echo "Tests failed. Blocking merge."
+            exit 1
+          else
+            echo "Tests passed. Allowing merge."
+            exit 0
+          fi
diff --git a/.github/workflows/golangci-lint.yml b/.github/workflows/golangci-lint.yml
--- a/.github/workflows/golangci-lint.yml
+++ b/.github/workflows/golangci-lint.yml
@@ -3,6 +3,7 @@ on:
   push:
     branches:
       - main
+      - ci-merge
 
 permissions:
   contents: read
@@ -52,3 +53,13 @@ jobs:
 
           # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
           # install-mode: "goinstall"
+
+      - name: Check fmt results
+        run: |
+            if [ ${{ job.status }} == 'failure' ]; then
+              echo "Tests failed. Blocking merge."
+              exit 1
+            else
+              echo "Tests passed. Allowing merge."
+              exit 0
+            fi
