add merge ci

diff --git a/.github/workflows/github-actions-es.yml b/.github/workflows/github-actions-es.yml
--- a/.github/workflows/github-actions-es.yml
+++ b/.github/workflows/github-actions-es.yml
@@ -4,7 +4,13 @@ name: GitHub Actions ES
 run-name: ${{ github.actor }} is push code to main 🚀
 on:
   push:
-    branches: [ "main" ]
+    branches:
+      - main
+      - merge
+  pull_request:
+    branches:
+      - main
+      - merge
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -21,3 +27,9 @@ jobs:
 
       - name: Test
         run: go test -v ./... -tags ci
+
+      - name: Check build and test results
+        if: failure()
+        run: |
+          echo "FMT build and test failed. Please fix the issues before merging."
+          exit 1
diff --git a/.github/workflows/golangci-lint.yml b/.github/workflows/golangci-lint.yml
--- a/.github/workflows/golangci-lint.yml
+++ b/.github/workflows/golangci-lint.yml
@@ -3,6 +3,11 @@ on:
   push:
     branches:
       - main
+      - merge
+  pull_request:
+    branches:
+      - main
+      - merge
 
 permissions:
   contents: read
@@ -52,3 +57,9 @@ jobs:
 
           # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
           # install-mode: "goinstall"
+
+      - name: Check fmt results
+        if: failure()
+        run: |
+          echo "FMT check failed. Please fix the issues before merging."
+          exit 1
