Add blocking merge

diff --git a/.github/workflows/github-actions-es.yml b/.github/workflows/github-actions-es.yml
--- a/.github/workflows/github-actions-es.yml
+++ b/.github/workflows/github-actions-es.yml
@@ -27,3 +27,10 @@ jobs:
 
       - name: Test
         run: go test -v ./... -tags ci
+
+      - name: Verify execution results
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Verification failed, blocking merge"
+            exit 1
+          fi
diff --git a/.github/workflows/golangci-lint.yml b/.github/workflows/golangci-lint.yml
--- a/.github/workflows/golangci-lint.yml
+++ b/.github/workflows/golangci-lint.yml
@@ -57,3 +57,10 @@ jobs:
 
           # Optional: The mode to install golangci-lint. It can be 'binary' or 'goinstall'.
           # install-mode: "goinstall"
+
+      - name: Verify execution results
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Verification failed, blocking merge"
+            exit 1
+          fi
